import { Document, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, Packer, BorderStyle, AlignmentType } from "docx";
import * as fs from "fs";
import * as path from "path";

async function generateDesignDocument() {
  const doc = new Document({
    title: "Perth Saver - Complete App Design & Code Reference",
    description: "Full design system, theme, and code documentation for Perth Saver PWA",
    creator: "Perth Saver Development Team",
    sections: [
      {
        children: [
          // Title
          new Paragraph({
            text: "PERTH SAVER",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "Complete App Design & Code Reference",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "Version 7.0 PRO • November 2025",
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "" }),

          // Overview Section
          new Paragraph({
            text: "1. PROJECT OVERVIEW",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Perth Saver is an AI-powered Progressive Web App (PWA) designed for Perth, Western Australia residents and businesses to achieve significant annual savings ($50K-100K). The platform provides tools and AI-driven advice for optimizing expenses across groceries, fuel, utilities, investments, tax, and business operations, with a focus on local Perth data and community insights.",
              }),
            ],
          }),
          new Paragraph({ text: "" }),

          // Tech Stack
          new Paragraph({
            text: "2. TECHNOLOGY STACK",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: "Frontend:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "• React 18 with TypeScript" }),
          new Paragraph({ text: "• Vite build system" }),
          new Paragraph({ text: "• Wouter for routing" }),
          new Paragraph({ text: "• TailwindCSS v4 for styling" }),
          new Paragraph({ text: "• shadcn/ui components (New York variant)" }),
          new Paragraph({ text: "• Framer Motion for animations" }),
          new Paragraph({ text: "• TanStack Query for server state" }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "Backend:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "• Express.js with TypeScript" }),
          new Paragraph({ text: "• PostgreSQL database (Neon Serverless)" }),
          new Paragraph({ text: "• Drizzle ORM for type-safe queries" }),
          new Paragraph({ text: "• Session-based authentication with bcrypt" }),
          new Paragraph({ text: "• Stripe for subscriptions" }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "AI Integration:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "• Multi-model AI orchestrator with intelligent failover:" }),
          new Paragraph({ text: "  - Primary: Claude 4.5 Sonnet" }),
          new Paragraph({ text: "  - Fallback 1: Gemini 3 Pro" }),
          new Paragraph({ text: "  - Fallback 2: OpenAI GPT-5.1" }),
          new Paragraph({ text: "" }),

          // Color Palette
          new Paragraph({
            text: "3. DESIGN TOKENS - COLOR PALETTE",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: "Primary Brand Colors:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "CYAN (Primary Accent):" }),
          new Paragraph({ text: "• cyan-50: #ecfeff" }),
          new Paragraph({ text: "• cyan-100: #cffafe" }),
          new Paragraph({ text: "• cyan-200: #a5f3fc" }),
          new Paragraph({ text: "• cyan-300: #67e8f9" }),
          new Paragraph({ text: "• cyan-400: #22d3ee" }),
          new Paragraph({ text: "• cyan-500: #06b6d4 (PRIMARY)" }),
          new Paragraph({ text: "• cyan-600: #0891b2" }),
          new Paragraph({ text: "• cyan-700: #0e7490" }),
          new Paragraph({ text: "• cyan-800: #155e75" }),
          new Paragraph({ text: "• cyan-900: #164e63" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "EMERALD (Secondary Accent):" }),
          new Paragraph({ text: "• emerald-50: #ecfdf5" }),
          new Paragraph({ text: "• emerald-100: #d1fae5" }),
          new Paragraph({ text: "• emerald-200: #a7f3d0" }),
          new Paragraph({ text: "• emerald-300: #6ee7b7" }),
          new Paragraph({ text: "• emerald-400: #34d399" }),
          new Paragraph({ text: "• emerald-500: #10b981 (PRIMARY)" }),
          new Paragraph({ text: "• emerald-600: #059669" }),
          new Paragraph({ text: "• emerald-700: #047857" }),
          new Paragraph({ text: "• emerald-800: #065f46" }),
          new Paragraph({ text: "• emerald-900: #064e3b" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "NEUTRAL COLORS (Dark Theme):" }),
          new Paragraph({ text: "• white: #ffffff" }),
          new Paragraph({ text: "• silver: #c0c0c0" }),
          new Paragraph({ text: "• black: #0a0a0a (Ultra-dark)" }),
          new Paragraph({ text: "• trueDark: #050505 (Page background)" }),
          new Paragraph({ text: "• obsidian: rgb(5, 5, 5)" }),
          new Paragraph({ text: "• charcoal: rgb(12, 12, 12)" }),
          new Paragraph({ text: "• onyx: rgb(18, 18, 18)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "SEMANTIC COLORS:" }),
          new Paragraph({ text: "• success: #10b981 (emerald)" }),
          new Paragraph({ text: "• warning: #f59e0b (amber)" }),
          new Paragraph({ text: "• error: #ef4444 (red)" }),
          new Paragraph({ text: "• info: #06b6d4 (cyan)" }),
          new Paragraph({ text: "" }),

          // Gradients
          new Paragraph({
            text: "4. GRADIENTS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "PRIMARY GRADIENT:" }),
          new Paragraph({ text: "linear-gradient(135deg, #06b6d4 0%, #10b981 100%)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "TEXT GRADIENT:" }),
          new Paragraph({ text: "linear-gradient(90deg, #06b6d4, #10b981)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "HERO GLOW:" }),
          new Paragraph({ text: "radial-gradient(ellipse at center, rgba(6, 182, 212, 0.15), transparent 70%)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLASS CARD:" }),
          new Paragraph({ text: "linear-gradient(135deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.02))" }),
          new Paragraph({ text: "" }),

          // Typography
          new Paragraph({
            text: "5. TYPOGRAPHY SCALE",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "DISPLAY (Hero headlines):" }),
          new Paragraph({ text: "• Font: Outfit" }),
          new Paragraph({ text: "• Size: clamp(2.5rem, 5vw, 4rem) [40px - 64px]" }),
          new Paragraph({ text: "• Weight: 800" }),
          new Paragraph({ text: "• Line height: 1.1" }),
          new Paragraph({ text: "• Letter spacing: -0.02em" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "TITLE (Section headers):" }),
          new Paragraph({ text: "• Font: Outfit" }),
          new Paragraph({ text: "• Size: clamp(1.5rem, 3vw, 2rem) [24px - 32px]" }),
          new Paragraph({ text: "• Weight: 700" }),
          new Paragraph({ text: "• Line height: 1.2" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "BODY (Main content):" }),
          new Paragraph({ text: "• Font: Inter" }),
          new Paragraph({ text: "• Size: 1rem (16px)" }),
          new Paragraph({ text: "• Weight: 400" }),
          new Paragraph({ text: "• Line height: 1.6" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "CAPTION (Secondary text):" }),
          new Paragraph({ text: "• Font: Inter" }),
          new Paragraph({ text: "• Size: 0.875rem (14px)" }),
          new Paragraph({ text: "• Weight: 500" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "MICRO (Labels, badges):" }),
          new Paragraph({ text: "• Font: Inter" }),
          new Paragraph({ text: "• Size: 0.75rem (12px)" }),
          new Paragraph({ text: "• Weight: 600" }),
          new Paragraph({ text: "" }),

          // Spacing
          new Paragraph({
            text: "6. SPACING SCALE (4px grid)",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "• 0.5: 2px    • 1: 4px    • 2: 8px    • 3: 12px    • 4: 16px" }),
          new Paragraph({ text: "• 5: 20px    • 6: 24px    • 8: 32px    • 10: 40px    • 12: 48px" }),
          new Paragraph({ text: "• 14: 56px    • 16: 64px    • 20: 80px    • 24: 96px    • 32: 128px" }),
          new Paragraph({ text: "" }),

          // Border Radius
          new Paragraph({
            text: "7. BORDER RADIUS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "• sm: 6px    • md: 8px    • lg: 12px    • xl: 16px" }),
          new Paragraph({ text: "• 2xl: 20px    • 3xl: 24px    • full: 9999px" }),
          new Paragraph({ text: "" }),

          // Shadows
          new Paragraph({
            text: "8. SHADOWS & GLOW EFFECTS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "CARD SHADOW:" }),
          new Paragraph({ text: "0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.2)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLOW CYAN:" }),
          new Paragraph({ text: "0 0 20px rgba(6, 182, 212, 0.4), 0 0 40px rgba(6, 182, 212, 0.2)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLOW EMERALD:" }),
          new Paragraph({ text: "0 0 20px rgba(16, 185, 129, 0.4), 0 0 40px rgba(16, 185, 129, 0.2)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLOW PRIMARY (Combined):" }),
          new Paragraph({ text: "0 0 30px rgba(6, 182, 212, 0.5), 0 0 60px rgba(16, 185, 129, 0.3)" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "FOCUS RING:" }),
          new Paragraph({ text: "0 0 0 2px rgba(6, 182, 212, 0.5)" }),
          new Paragraph({ text: "" }),

          // Glassmorphism
          new Paragraph({
            text: "9. GLASSMORPHISM EFFECTS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLASS CARD:" }),
          new Paragraph({ text: ".glass-card {" }),
          new Paragraph({ text: "  background-color: rgba(5, 5, 5, 0.6);" }),
          new Paragraph({ text: "  backdrop-filter: blur(14px) saturate(140%);" }),
          new Paragraph({ text: "  border: 1px solid rgba(6, 182, 212, 0.12);" }),
          new Paragraph({ text: "  border-radius: 1.5rem;" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "GLASS STRONG:" }),
          new Paragraph({ text: ".glass-strong {" }),
          new Paragraph({ text: "  background-color: rgba(18, 18, 18, 0.85);" }),
          new Paragraph({ text: "  backdrop-filter: blur(16px) saturate(160%);" }),
          new Paragraph({ text: "  border: 1px solid rgba(6, 182, 212, 0.15);" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),

          // Animation
          new Paragraph({
            text: "10. ANIMATION TIMING",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "DURATIONS:" }),
          new Paragraph({ text: "• instant: 0ms    • fast: 150ms    • normal: 300ms    • slow: 500ms    • slower: 700ms" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "EASING FUNCTIONS:" }),
          new Paragraph({ text: "• easeIn: cubic-bezier(0.4, 0, 1, 1)" }),
          new Paragraph({ text: "• easeOut: cubic-bezier(0, 0, 0.2, 1)" }),
          new Paragraph({ text: "• easeInOut: cubic-bezier(0.4, 0, 0.2, 1)" }),
          new Paragraph({ text: "• spring: cubic-bezier(0.175, 0.885, 0.32, 1.275)" }),
          new Paragraph({ text: "" }),

          // CSS Classes
          new Paragraph({
            text: "11. KEY CSS UTILITY CLASSES",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/* Premium Button */" }),
          new Paragraph({ text: ".btn-premium {" }),
          new Paragraph({ text: "  background: linear-gradient(135deg, #06B6D4 0%, #10B981 100%);" }),
          new Paragraph({ text: "  box-shadow: 0 4px 20px rgba(6, 182, 212, 0.4);" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/* Text Gradient */" }),
          new Paragraph({ text: ".text-gradient {" }),
          new Paragraph({ text: "  background: linear-gradient(135deg, #22D3EE 0%, #10B981 50%, #06B6D4 100%);" }),
          new Paragraph({ text: "  -webkit-background-clip: text;" }),
          new Paragraph({ text: "  -webkit-text-fill-color: transparent;" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/* Glow Text */" }),
          new Paragraph({ text: ".glow-text {" }),
          new Paragraph({ text: "  text-shadow: 0 0 10px rgba(6, 182, 212, 0.8), 0 0 20px rgba(6, 182, 212, 0.5);" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/* Floating Animation */" }),
          new Paragraph({ text: "@keyframes float {" }),
          new Paragraph({ text: "  0%, 100% { transform: translateY(0px); }" }),
          new Paragraph({ text: "  50% { transform: translateY(-10px); }" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/* Pulse Glow */" }),
          new Paragraph({ text: "@keyframes pulse-glow {" }),
          new Paragraph({ text: "  0%, 100% { box-shadow: 0 0 20px rgba(6, 182, 212, 0.3); }" }),
          new Paragraph({ text: "  50% { box-shadow: 0 0 40px rgba(6, 182, 212, 0.5); }" }),
          new Paragraph({ text: "}" }),
          new Paragraph({ text: "" }),

          // React Components
          new Paragraph({
            text: "12. KEY REACT COMPONENTS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "SafeImage Component:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "Asset reliability layer with:" }),
          new Paragraph({ text: "• Automatic fallback to SVG on load failure" }),
          new Paragraph({ text: "• Cache-bust querystring for preview builds" }),
          new Paragraph({ text: "• Loading state handling" }),
          new Paragraph({ text: "• Retry mechanism for transient failures" }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "ThemeHealthCheck Component:",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({ text: "Dev panel (Ctrl+Shift+T) for diagnostics:" }),
          new Paragraph({ text: "• Token version verification" }),
          new Paragraph({ text: "• CSS variables presence check" }),
          new Paragraph({ text: "• Logo asset resolution" }),
          new Paragraph({ text: "• Layout element verification" }),
          new Paragraph({ text: "• Typography font check" }),
          new Paragraph({ text: "• Framer Motion activity check" }),
          new Paragraph({ text: "" }),

          // Product Database
          new Paragraph({
            text: "13. PERTH PRODUCT DATABASE (70+ Items)",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "CATEGORIES:" }),
          new Paragraph({ text: "• Dairy & Eggs (7 items): Milk, Eggs, Butter, Cheese, Yogurt, Cream" }),
          new Paragraph({ text: "• Bread & Bakery (4 items): White, Wholemeal, Sourdough, Wraps" }),
          new Paragraph({ text: "• Meat & Poultry (8 items): Chicken, Beef, Pork, Lamb, Sausages, Bacon" }),
          new Paragraph({ text: "• Seafood (3 items): Salmon, Prawns, Fish" }),
          new Paragraph({ text: "• Fruits (8 items): Bananas, Apples, Oranges, Berries, Grapes, Avocados, Lemons" }),
          new Paragraph({ text: "• Vegetables (13 items): Potatoes, Onions, Carrots, Broccoli, Tomatoes, Lettuce, etc." }),
          new Paragraph({ text: "• Pantry (16 items): Rice, Pasta, Oil, Sugar, Flour, Cereals, Spreads, Coffee, Tea" }),
          new Paragraph({ text: "• Beverages (3 items): Soft drinks, Juice, Water" }),
          new Paragraph({ text: "• Frozen Foods (4 items): Ice cream, Peas, Chips, Pizza" }),
          new Paragraph({ text: "• Snacks (4 items): Chips, Chocolate, Tim Tams, Nuts" }),
          new Paragraph({ text: "• Household (6 items): Toilet paper, Paper towels, Cleaning products" }),
          new Paragraph({ text: "• Baby & Pet (4 items): Wipes, Nappies, Dog food, Cat food" }),
          new Paragraph({ text: "• Personal Care (4 items): Shampoo, Toothpaste, Deodorant, Soap" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "STORES COVERED:" }),
          new Paragraph({ text: "• Woolworths • Coles • ALDI • IGA • Spudshed • Costco Perth" }),
          new Paragraph({ text: "" }),

          // Features
          new Paragraph({
            text: "14. CORE FEATURES",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "• AI Financial Coach with animated avatar" }),
          new Paragraph({ text: "• Basket Optimizer v2 (multi-store split optimization)" }),
          new Paragraph({ text: "• WA Specials Radar for hidden deals" }),
          new Paragraph({ text: "• Wealth Optimizer for investments" }),
          new Paragraph({ text: "• Tax Deductions Scanner" }),
          new Paragraph({ text: "• Fleet Fuel Manager for businesses" }),
          new Paragraph({ text: "• Subscription Audit tool" }),
          new Paragraph({ text: "• Business Hub for commercial users" }),
          new Paragraph({ text: "• Referral System with social sharing" }),
          new Paragraph({ text: "• Achievement badges and shareable cards" }),
          new Paragraph({ text: "• PWA with offline support" }),
          new Paragraph({ text: "• Stripe subscription integration (Starter/Premium/Family tiers)" }),
          new Paragraph({ text: "" }),

          // Breakpoints
          new Paragraph({
            text: "15. RESPONSIVE BREAKPOINTS",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "• sm: 640px    • md: 768px    • lg: 1024px    • xl: 1280px    • 2xl: 1536px" }),
          new Paragraph({ text: "" }),

          // Z-Index
          new Paragraph({
            text: "16. Z-INDEX SCALE",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "• base: 0    • dropdown: 10    • sticky: 20    • fixed: 30" }),
          new Paragraph({ text: "• modalBackdrop: 40    • modal: 50    • popover: 60    • tooltip: 70    • toast: 80" }),
          new Paragraph({ text: "" }),

          // File Structure
          new Paragraph({
            text: "17. PROJECT STRUCTURE",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/client" }),
          new Paragraph({ text: "  /src" }),
          new Paragraph({ text: "    /components - Reusable UI components" }),
          new Paragraph({ text: "    /lib - Utilities, tokens, helpers" }),
          new Paragraph({ text: "    /pages - Route pages" }),
          new Paragraph({ text: "    /hooks - Custom React hooks" }),
          new Paragraph({ text: "    index.css - Global styles & theme" }),
          new Paragraph({ text: "    App.tsx - Root component & routing" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/server" }),
          new Paragraph({ text: "  routes.ts - API endpoints" }),
          new Paragraph({ text: "  storage.ts - Database operations" }),
          new Paragraph({ text: "  aiOrchestrator.ts - AI model failover" }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "/shared" }),
          new Paragraph({ text: "  schema.ts - Drizzle database schema & Zod validators" }),
          new Paragraph({ text: "" }),

          // Footer
          new Paragraph({ text: "" }),
          new Paragraph({ text: "---" }),
          new Paragraph({
            text: "Perth Saver © 2025 - Built for Perth, Western Australia",
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "Design System v7.0 PRO",
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = path.join(process.cwd(), "Perth_Saver_Design_Reference.docx");
  fs.writeFileSync(outputPath, buffer);
  console.log(`✅ Document generated: ${outputPath}`);
}

generateDesignDocument().catch(console.error);
